name: Build and deploy

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main, deploy-for-issues]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check urls
        run: if grep -q localhost ozon/src/utils/urls/urls.js; then exit 999; fi

      - name: Install deps
        run: npm i

      - name: Linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./ozon

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Upload to hotbox
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --endpoint-url https://hb.bizmrg.com --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: duckluckbreakout
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
